language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t carrenoj1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true carrenoj1/docker-react npm run test
# run tests, leave and continue 
deploy:
  provider: elasticbeanstalk
  edge: true
    
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-766168668673"
  bucket_path: "docker" 

  on:
      branch: master

  access_key_id: $AWS_ACCESS_KEY
  
  secret_access_key: $AWS_SECRET_KEY

