
language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t carrenoj1/docker-react -f Dockerfile.dev .

script:     
    - docker run -e CI=true carrenoj1/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  edge: true
    
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-766168668673" 

  on:
      branch: master

  access_key_id: $AWS_ACCESS_KEY
  
  secret_access_key: $AWS_SECRET_KEY
